spring:
  application:
    name:
      resilience4j-store-app
  jackson:
    mapper:
      accept-case-insensitive-enums: true

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com:
      pictet:
        technologies:
          resilience:
            resilience4j:
              store:
                provider:
                  exchangerate:
                    ExchangeRateClient: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 500
  retry:
    retry-aspect-order: 1000

resilience4j.retry:
  configs:
    default:
      # The maximum number of attempts
      maxAttempts: 3
      # A fixed wait duration between retry attempts
      waitDuration: 100
      # Enable exponential backoff
      enableExponentialBackoff: true
      # Time multiplier
      exponentialBackoffMultiplier: 2
      # List of Throwable classes that are recorded as a failure and thus are retried.
      retryExceptions:
        - feign.RetryableException
        - feign.FeignException.FeignServerException
        - feign.FeignException.TooManyRequests
        - java.io.IOException
        - java.util.concurrent.TimeoutException
      # Configures a list of Throwable classes that are ignored and thus are not retried
      ignoreExceptions:
        - feign.FeignException.NotImplemented

resilience4j.circuitbreaker:
  instances:
    exchangeRateService-get:
      # Configures the failure rate threshold in percentage.
      failureRateThreshold: 50
      # Configures the type of the sliding window which is used to record the outcome of calls when
      # the CircuitBreaker is closed.
      slidingWindowType: COUNT_BASED
      #  size of the sliding window which is used to record the outcome of calls when the CircuitBreaker is closed.
      slidingWindowSize: 20
      # Configures the minimum number of calls which are required (per sliding window period)
      # before the CircuitBreaker can calculate the error rate or slow call rate.
      minimumNumberOfCalls: 5
      # Configures the number of permitted calls when the CircuitBreaker is half open.
      permittedNumberOfCallsInHalfOpenState: 10
      # The time that the CircuitBreaker should wait before transitioning from open to half-open.
      waitDurationInOpenState: 10000


resilience4j.bulkhead:
  configs:
    default:
      # Max amount of parallel executions allowed by the bulkhead
      maxConcurrentCalls: 10
      # Max amount of time a thread should be blocked for when attempting to enter a saturated bulkhead.
      maxWaitDuration: 10ms


resilience4j.thread-pool-bulkhead:
  configs:
    default:
      # Configures the max thread pool size
      maxThreadPoolSize: 4
      # Configures the core thread pool size
      coreThreadPoolSize: 2
      # Capacity of the queue.
      queueCapacity: 2
      # When the number of threads is greater than the core, this is the maximum
      # time that excess idle threads will wait for new tasks before terminating.
      keepAliveDuration: 20ms

#resilience4j.ratelimiter:
#  configs:
#    default:
#      registerHealthIndicator: false
#      limitForPeriod: 10
#      limitRefreshPeriod: 1s
#      timeoutDuration: 0
#      eventConsumerBufferSize: 100
#  instances:
#    backendA:
#      baseConfig: default
#    backendB:
#      limitForPeriod: 6
#      limitRefreshPeriod: 500ms
#      timeoutDuration: 3s
#
#resilience4j.timelimiter:
#  configs:
#    default:
#      cancelRunningFuture: false
#      timeoutDuration: 2s
#  instances:
#    backendA:
#      baseConfig: default
#    backendB:
#      baseConfig: default
