spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    com:
      pictet:
        technologies:
          resilience:
            resilience4j:
              store:
                provider:
                  ExchangeRateClient: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

